// Generates src/wordmark.ts: the Commute wordmark sampled onto the dot lattice,
// so the footer beat can light those cells in the existing field.
//
// Run once and COMMIT the output (same contract as src/network.ts) — the page
// must not rasterize SVG at runtime.
//
//   node scripts/generateWordmark.mjs
//
// Path data is read straight out of index.html's nav logo, so the mask can never
// drift from the wordmark the rest of the page shows. Rasterizing goes through a
// real browser's Path2D (via the Playwright already in the workspace) rather than
// a hand-rolled SVG parser: these glyphs are all cubic béziers.
import fs from 'node:fs'
import path from 'node:path'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.join(here, '..')

// Playwright belongs to apps/web, not this package. Resolve it from there rather
// than adding a dependency for a script that runs once per logo change. pnpm's
// isolated store means it is NOT resolvable from the workspace root.
const require = createRequire(path.join(root, '../web/package.json'))
const { chromium } = require('playwright')

// Target lattice size. 100x17 was chosen by eye against a dot-scale preview:
// at 90x15 the counters in C/o/e start closing up, and anything larger buys no
// legibility while eating into the clear band below the network.
const COLS = 100
const ROWS = 17
// A cell lights when at least this fraction of it is inside a glyph.
const COVERAGE = 0.5
// Supersampling factor per cell when measuring coverage.
const SS = 8

function readWordmark() {
  const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8')
  const svg = html.match(/<svg[^>]*viewBox="([^"]+)"[^>]*>([\s\S]*?)<\/svg>/)
  if (!svg) throw new Error('no <svg> with a viewBox found in index.html')
  const [, , vbW, vbH] = svg[1].split(/\s+/).map(Number)
  const paths = [...svg[2].matchAll(/<path d="([^"]+)"/g)].map(m => m[1])
  if (paths.length === 0) throw new Error('no <path d> found in the wordmark svg')
  return { vbW, vbH, paths }
}

const { vbW, vbH, paths } = readWordmark()

const browser = await chromium.launch()
const page = await browser.newPage()
const { cells, preview } = await page.evaluate(
  ({ paths, vbW, vbH, cols, rows, ss, coverage }) => {
    const canvas = document.createElement('canvas')
    canvas.width = cols * ss
    canvas.height = rows * ss
    const ctx = canvas.getContext('2d')
    ctx.fillStyle = '#000'
    ctx.fillRect(0, 0, canvas.width, canvas.height)
    ctx.fillStyle = '#fff'
    ctx.setTransform(canvas.width / vbW, 0, 0, canvas.height / vbH, 0, 0)
    for (const d of paths) ctx.fill(new Path2D(d))

    const px = ctx.getImageData(0, 0, canvas.width, canvas.height).data
    const cells = []
    const preview = []
    for (let row = 0; row < rows; row++) {
      let line = ''
      for (let col = 0; col < cols; col++) {
        let hits = 0
        for (let y = 0; y < ss; y++) {
          for (let x = 0; x < ss; x++) {
            const i = ((row * ss + y) * canvas.width + (col * ss + x)) * 4
            if (px[i] > 127) hits++
          }
        }
        const lit = hits / (ss * ss) >= coverage
        if (lit) cells.push([col, row])
        line += lit ? '#' : '.'
      }
      preview.push(line)
    }
    return { cells, preview }
  },
  { paths, vbW, vbH, cols: COLS, rows: ROWS, ss: SS, coverage: COVERAGE }
)
await browser.close()

const out = `// GENERATED by scripts/generateWordmark.mjs — do not edit by hand.
// The Commute wordmark sampled onto the dot lattice, so the footer beat can
// light these cells in the existing dead-dot field instead of drawing type over
// it. Regenerate after any change to the logo:
//
//   node scripts/generateWordmark.mjs
//
${preview.map(l => `// ${l}`).join('\n')}

/** Lit cells as [col, row], relative to the wordmark's own top-left origin. */
export const WORDMARK_CELLS: readonly (readonly [number, number])[] = [
${cells.map(([c, r]) => `  [${c}, ${r}]`).join(',\n')}
]

/** Extent of the wordmark in lattice cells. */
export const WORDMARK_SIZE = { cols: ${COLS}, rows: ${ROWS} } as const
`

fs.writeFileSync(path.join(root, 'src/wordmark.ts'), out)
console.log(`wrote src/wordmark.ts — ${cells.length} lit cells, ${COLS}x${ROWS}`)
console.log(preview.join('\n'))
