import globals from 'globals'
import { defineConfig, globalIgnores } from 'eslint/config'
import pluginJs from '@eslint/js'
import tseslint from 'typescript-eslint'
import stylistic from '@stylistic/eslint-plugin'

export default defineConfig([
  {
    languageOptions: { globals: globals.browser },
    files: ['apps/**/*.ts', 'apps/**/*.tsx']
  },
  {
    // Build-time and verification scripts run under Node. Several also evaluate
    // code inside a headless browser — generateWordmark.mjs rasterizes via
    // Path2D, and apps/web's verify-* scripts drive the app through Playwright
    // — so they legitimately reference both sets of globals.
    files: [
      'apps/data-platform/scripts/**/*.{js,mjs,ts}',
      'apps/web/scripts/**/*.{js,mjs,ts}'
    ],
    languageOptions: { globals: { ...globals.node, ...globals.browser } }
  },
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
  stylistic.configs.customize({
    quotes: 'single',
    semi: false,
    indent: 2,
    commaDangle: 'never',
    braceStyle: '1tbs'
  }),
  globalIgnores([
    // Session scratch space, git-ignored but still visible to eslint.
    '.remember/**/*',
    'apps/api/.wrangler/**/*',
    'apps/api/dist/**/*',
    'apps/data-platform/.wrangler/**/*',
    'apps/data-platform/dist/**/*',
    'apps/opengraph/.wrangler/**/*',
    'apps/opengraph/dist/**/*',
    // Generated data: a vendored base64 font and the SVG card template string.
    'apps/opengraph/src/assets/font.ts',
    'apps/opengraph/src/assets/og-fare-template.ts',
    // Generated by apps/api generate:dataplatform-network — the baked rail
    // topology, written by JSON.stringify. Formatting it would be undone by the
    // next regeneration.
    'apps/data-platform/src/network.ts',
    'apps/web/build/**/*',
    'apps/web/.react-router/**/*',
    'apps/web/.wrangler/**/*'
  ])
])
