import * as fs from 'node:fs'
import { execFileSync } from 'node:child_process'
import { TOPOLOGY } from '../data/topology'

/*
 * Prunes stale `stationLines` memberships: rows for a MANAGED BRT corridor (a
 * line declared in TOPOLOGY) whose station is NOT in that line's topology
 * (path / pathReverse / branches). Those are protest-day / temporary reroute
 * artifacts — the station isn't part of the line's normal service, so it
 * shouldn't render as a stop on that line's page.
 *
 * SCOPE: the emitted DELETE covers only the CONFIRMED artifacts in PRUNE_PAIRS
 * below (reviewed by hand). The audit surfaces stale rows on other managed lines
 * too, but several are TOPOLOGY GAPS — real service the generator missed (e.g.
 * `13 <- Puri Beta 2`, its origin terminus) — which must be fixed in the topology,
 * NOT pruned. See STALE_STATIONLINES.md at the repo root for the full classified
 * list. Add a `lineCode|station` to PRUNE_PAIRS only once confirmed an artifact.
 *
 * Feeder / Mikrotrans line memberships are never touched (those lines aren't in
 * TOPOLOGY, so they're not "managed" and never enter the stale set).
 *
 * The audit reads the LOCAL D1 (miniflare) via wrangler to cross-check the
 * hardcoded PRUNE_PAIRS and report deferred rows. Apply the emitted SQL:
 *   wrangler d1 execute commute --local  --file=src/db/scripts/prune_stationlines.sql
 *   wrangler d1 execute commute --remote --file=src/db/scripts/prune_stationlines.sql
 * Re-run: pnpm --filter api generate:prune-stationlines
 */
const OUTPUT_SQL_PATH = `${__dirname}/prune_stationlines.sql`
const CWD = `${__dirname}/../../..` // apps/api

// Confirmed reroute / wrong-line `lineCode|station` artifacts to prune (reviewed
// against STALE_STATIONLINES.md, 2026-07-20). Kept DB-independent (a hardcoded
// allowlist, not "whatever is stale in the local D1 right now") so the emitted
// DELETE is complete and idempotent on local, remote, and fresh reseeds alike.
//
//   Koridor 1 western protest-day reroute (the nine): Petamburan, Rawa Barat,
//     Tarakan, Kota Bambu (N/S), Kemanggisan (N/S), Pasar Santa, Tomang Raya.
//   4  Bermis            — actually a Koridor 2 halte
//   5C/7F Gambir/Istiqlal — Koridor 2 haltes
//   6V Kejaksaan Agung    — no normal K6V pass
//   8  Grogol/Roxy        — original alignment, rerouted for MRT construction
//
// NOT pruned (kept as real service / topology gaps to fix): 3 Monas; 4/4D
// Simpang Pramuka + Halte Manggarai Temporer B-codes; 4 Simpang Pramuka (H00181P,
// a K4 topology gap); 6A/6B Kebon Sirih; 9A Tanjung Duren; 13 Puri Beta 2.
const PRUNE_PAIRS = new Set([
  '1|H00036C', '1|H00192P', '1|H00201P', '1|H00204S', '1|H00209S', // K1 reroute…
  '1|H00220S', '1|H00224S', '1|H00249P', '1|H00250P', //            …(nine total)
  '4|H00011P', // Bermis
  '5C|H00058P', '5C|H00078P', // Gambir, Istiqlal
  '6V|H00266P', // Kejaksaan Agung
  '7F|H00058P', '7F|H00078P', // Gambir, Istiqlal
  '8|H00070P', '8|H00200P' // Grogol, Roxy
])

// stationLines.id follows `${stationId}-${lineCode}` (e.g. TJ-H00192P-1).
const rowId = (pair: string): string => {
  const [line, code] = pair.split('|')
  return `TJ-${code}-${line}`
}

// Valid (lineCode, station) pairs from the TJ topology — the ground truth for
// what each managed line serves on a normal day.
const managedLines = new Set(TOPOLOGY.filter(t => t.operator === 'TJ').map(t => t.lineCode))
const validPairs = new Set<string>()
for (const t of TOPOLOGY) {
  if (t.operator !== 'TJ') continue
  for (const s of t.path) validPairs.add(`${t.lineCode}|${s.station}`)
  for (const s of t.pathReverse ?? []) validPairs.add(`${t.lineCode}|${s.station}`)
  for (const b of t.branches ?? []) for (const s of b.path) validPairs.add(`${t.lineCode}|${s.station}`)
}

// Pull every TJ stationLines row from the local D1.
const raw = execFileSync('npx', [
  'wrangler', 'd1', 'execute', 'commute', '--local', '--json',
  '--command', 'SELECT id, stationId, lineCode FROM stationLines WHERE stationId LIKE \'TJ-%\''
], { encoding: 'utf-8', cwd: CWD })
const rows = (JSON.parse(raw)[0].results ?? []) as { id: string, stationId: string, lineCode: string }[]

// The emitted DELETE is built from PRUNE_PAIRS (DB-independent), so it's complete
// and idempotent on any DB regardless of what's currently pruned locally.
const ids = [...PRUNE_PAIRS].map(p => `'${rowId(p)}'`).join(', ')
const sql
  = '-- Prune stale stationLines memberships (managed line, station not in its topology).\n'
    + '-- Confirmed reroute / wrong-line artifacts only; topology-gap rows are kept (STALE_STATIONLINES.md).\n'
    + '-- Generated by generatePruneStationLinesSQL.ts — do not edit by hand.\n'
    + `DELETE FROM stationLines WHERE id IN (${ids});\n`

fs.writeFileSync(OUTPUT_SQL_PATH, sql)

// Cross-check against the live local D1: warn if a prune target isn't actually a
// stale row (topology now covers it, or the id is wrong), and list the stale rows
// we're deliberately deferring for review.
const stale = rows.filter(r => managedLines.has(r.lineCode) && !validPairs.has(`${r.lineCode}|${r.stationId.slice(3)}`))
const staleKeys = new Set(stale.map(r => `${r.lineCode}|${r.stationId.slice(3)}`))
const livePruneable = new Set(rows.map(r => r.id))
const deferred = stale.filter(r => !PRUNE_PAIRS.has(`${r.lineCode}|${r.stationId.slice(3)}`))

console.log(`Wrote DELETE for ${PRUNE_PAIRS.size} confirmed artifact rows to "${OUTPUT_SQL_PATH}".`)
// A target that's neither currently in the DB nor in the stale set is worth a look.
for (const p of PRUNE_PAIRS) {
  const id = rowId(p)
  if (!staleKeys.has(p) && !livePruneable.has(id)) console.log(`  note: ${p} (${id}) not present in local D1 (already pruned, or stale-check drifted)`)
  else if (!staleKeys.has(p) && livePruneable.has(id)) console.warn(`  WARN: ${p} exists but is NO LONGER stale (topology now serves it?) — re-review before pruning`)
}
if (deferred.length > 0) {
  const byLine = [...new Set(deferred.map(r => r.lineCode))].sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))
  console.log(`  DEFERRED (still stale, kept for review — see STALE_STATIONLINES.md) on lines: ${byLine.join(', ')}`)
}
console.log(`Wrote "${OUTPUT_SQL_PATH}".`)
