import * as fs from 'node:fs'
import { TOPOLOGY } from '../data/topology'

/*
 * Emits a DELETE that prunes non-routable edges from the `edges` table — the
 * ~3.5k rows for non-BRT TransJakarta feeder / Mikrotrans lines that were
 * imported (tj_edges_insert.sql) but are NOT declared in TOPOLOGY. Their haltes
 * are already hidden (searchable=0), and EdgeRepository.getGraphInputs already
 * allowlists routable lineCodes at query time — this just removes the dead rows
 * from the DB so the table matches what actually routes.
 *
 * The routable set is derived from TOPOLOGY (the single source of truth shared
 * with EdgeRepository), so adding a corridor there automatically keeps its edges.
 * The premium-fare Soekarno-Hatta line A stays in the DB (it's real track, just
 * not routed in v1), so it is NOT pruned here.
 *
 * Idempotent. Apply with:
 *   wrangler d1 execute commute --local  --file=src/db/scripts/prune_feeder_edges.sql
 *   wrangler d1 execute commute --remote --file=src/db/scripts/prune_feeder_edges.sql
 * Re-run generation: pnpm --filter api generate:prune-feeder-edges
 */
const OUTPUT_SQL_PATH = `${__dirname}/prune_feeder_edges.sql`

// Routable lineCodes = every line declared in TOPOLOGY. Line A is real track but
// unrouted in v1; it's kept in the DB, so it stays in the KEEP set here.
const routableLineCodes = [...new Set(TOPOLOGY.map(t => t.lineCode))].sort()

const inList = routableLineCodes.map(code => `'${code.replace(/'/g, '\'\'')}'`).join(', ')

const sql
  = '-- Prune non-routable feeder/Mikrotrans edges (lines absent from TOPOLOGY).\n'
    + '-- Generated by generatePruneFeederEdgesSQL.ts — do not edit by hand.\n'
    + `DELETE FROM edges WHERE lineCode NOT IN (${inList});\n`

fs.writeFileSync(OUTPUT_SQL_PATH, sql)
console.log(`Wrote prune DELETE keeping ${routableLineCodes.length} routable lineCodes to "${OUTPUT_SQL_PATH}".`)
console.log(`  keep: ${routableLineCodes.join(', ')}`)
