-- Prune non-routable feeder/Mikrotrans edges (lines absent from TOPOLOGY).
-- Generated by generatePruneFeederEdgesSQL.ts — do not edit by hand.
DELETE FROM edges WHERE lineCode NOT IN ('1', '10', '10D', '10H', '11', '12', '13', '13B', '13E', '14', '2', '2A', '3', '3F', '3H', '4', '4D', '5', '5C', '6', '6A', '6B', '6V', '7', '7F', '8', '9', '9A', '9C', '9N', 'A', 'B', 'BK', 'C', 'CB', 'L13E', 'M', 'R', 'S', 'T', 'TP');
