-- Prune stale stationLines memberships (managed line, station not in its topology).
-- Confirmed reroute / wrong-line artifacts only; topology-gap rows are kept (STALE_STATIONLINES.md).
-- Generated by generatePruneStationLinesSQL.ts — do not edit by hand.
DELETE FROM stationLines WHERE id IN ('TJ-H00036C-1', 'TJ-H00192P-1', 'TJ-H00201P-1', 'TJ-H00204S-1', 'TJ-H00209S-1', 'TJ-H00220S-1', 'TJ-H00224S-1', 'TJ-H00249P-1', 'TJ-H00250P-1', 'TJ-H00011P-4', 'TJ-H00058P-5C', 'TJ-H00078P-5C', 'TJ-H00266P-6V', 'TJ-H00058P-7F', 'TJ-H00078P-7F', 'TJ-H00070P-8', 'TJ-H00200P-8');
