-- Generated by db/scripts/generateStationScoresSQL.ts. Do not edit by hand.
-- Station search/picker ranking. Anchored scores are measured ridership
-- (db/data/ridership.ts); the rest are service+structure estimates.
-- Apply AFTER any TJ reseed, then bump API_VERSION in wrangler.toml.

UPDATE stations SET score = 19, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-AC';
UPDATE stations SET score = 46, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-AK';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-BBN';
UPDATE stations SET score = 50, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-BJD';
UPDATE stations SET score = 77, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-BKS'; -- measured
UPDATE stations SET score = 46, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-BKST';
UPDATE stations SET score = 30, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-BOI';
UPDATE stations SET score = 85, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-BOO'; -- measured
UPDATE stations SET score = 39, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-BPR';
UPDATE stations SET score = 46, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-BUA';
UPDATE stations SET score = 47, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-CBN';
UPDATE stations SET score = 37, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-CC';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-CE';
UPDATE stations SET score = 46, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-CIT';
UPDATE stations SET score = 37, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-CJT';
UPDATE stations SET score = 47, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-CKI';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-CKL';
UPDATE stations SET score = 49, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-CKR';
UPDATE stations SET score = 37, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-CKY';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-CLG';
UPDATE stations SET score = 47, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-CLT';
UPDATE stations SET score = 37, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-CSK';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-CT';
UPDATE stations SET score = 78, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-CTA'; -- measured
UPDATE stations SET score = 37, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-CTR';
UPDATE stations SET score = 46, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-CUK';
UPDATE stations SET score = 61, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-CW';
UPDATE stations SET score = 37, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-DAR';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-DL';
UPDATE stations SET score = 47, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-DP';
UPDATE stations SET score = 47, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-DPB';
UPDATE stations SET score = 47, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-DRN';
UPDATE stations SET score = 65, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-DU';
UPDATE stations SET score = 47, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-GDD';
UPDATE stations SET score = 36, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-GGL';
UPDATE stations SET score = 46, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-GST';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-GW';
UPDATE stations SET score = 79, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-JAKK';
UPDATE stations SET score = 47, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-JAY';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-JBU';
UPDATE stations SET score = 19, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-JIS';
UPDATE stations SET score = 37, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-JMU';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-JN';
UPDATE stations SET score = 55, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-JNG';
UPDATE stations SET score = 37, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-JTK';
UPDATE stations SET score = 50, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-JUA';
UPDATE stations SET score = 46, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-KAT';
UPDATE stations SET score = 43, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-KBY';
UPDATE stations SET score = 30, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-KDS';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-KEN';
UPDATE stations SET score = 49, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-KLD';
UPDATE stations SET score = 46, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-KLDB';
UPDATE stations SET score = 46, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-KMO';
UPDATE stations SET score = 46, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-KMT';
UPDATE stations SET score = 54, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-KPB';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-KRA';
UPDATE stations SET score = 46, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-KRI';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-KT';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-KTA';
UPDATE stations SET score = 47, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-LNA';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-LPN';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-MER';
UPDATE stations SET score = 47, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-MGB';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-MGW';
UPDATE stations SET score = 37, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-MJ';
UPDATE stations SET score = 95, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-MRI'; -- measured
UPDATE stations SET score = 49, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-MTR';
UPDATE stations SET score = 50, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-NMO';
UPDATE stations SET score = 37, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-PDJ';
UPDATE stations SET score = 50, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-PDRG';
UPDATE stations SET score = 30, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-PI';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-PL';
UPDATE stations SET score = 37, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-PLM';
UPDATE stations SET score = 47, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-POC';
UPDATE stations SET score = 49, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-POK';
UPDATE stations SET score = 37, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-PRP';
UPDATE stations SET score = 62, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-PSE';
UPDATE stations SET score = 30, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-PSG';
UPDATE stations SET score = 47, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-PSM';
UPDATE stations SET score = 47, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-PSMB';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-PWS';
UPDATE stations SET score = 46, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-RJW';
UPDATE stations SET score = 40, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-RK';
UPDATE stations SET score = 37, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-RU';
UPDATE stations SET score = 36, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-RW';
UPDATE stations SET score = 37, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-SDM';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-SK';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-SLO';
UPDATE stations SET score = 37, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-SRP';
UPDATE stations SET score = 79, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-SUD'; -- measured
UPDATE stations SET score = 25, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-SUDB'; -- measured
UPDATE stations SET score = 47, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-SW';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-SWT';
UPDATE stations SET score = 46, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-TB';
UPDATE stations SET score = 47, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-TEB';
UPDATE stations SET score = 37, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-TEJ';
UPDATE stations SET score = 37, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-TGS';
UPDATE stations SET score = 100, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-THB'; -- measured
UPDATE stations SET score = 33, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-TKO';
UPDATE stations SET score = 46, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-TLM';
UPDATE stations SET score = 33, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-TNG';
UPDATE stations SET score = 47, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-TNT';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-TOJB';
UPDATE stations SET score = 25, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-TPK';
UPDATE stations SET score = 30, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-TTI';
UPDATE stations SET score = 47, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-UI';
UPDATE stations SET score = 47, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-UP';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-WJ';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-WLT';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-WT';
UPDATE stations SET score = 0, updatedAt = CURRENT_TIMESTAMP WHERE id = 'KCI-YK';
UPDATE stations SET score = 5, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJ-BVS';
UPDATE stations SET score = 5, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJ-BVU';
UPDATE stations SET score = 5, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJ-EQS';
UPDATE stations SET score = 8, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJ-PGD';
UPDATE stations SET score = 8, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJ-PUM';
UPDATE stations SET score = 11, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJ-VEL';
UPDATE stations SET score = 23, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJBDB-BEK';
UPDATE stations SET score = 43, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJBDB-CIL';
UPDATE stations SET score = 23, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJBDB-CK1';
UPDATE stations SET score = 23, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJBDB-CK2';
UPDATE stations SET score = 52, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJBDB-CKK'; -- measured
UPDATE stations SET score = 23, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJBDB-CRC';
UPDATE stations SET score = 43, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJBDB-CWG';
UPDATE stations SET score = 61, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJBDB-DKA'; -- measured
UPDATE stations SET score = 23, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJBDB-HAL';
UPDATE stations SET score = 58, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJBDB-HAR'; -- measured
UPDATE stations SET score = 23, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJBDB-JBU';
UPDATE stations SET score = 26, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJBDB-JTM';
UPDATE stations SET score = 26, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJBDB-KAM';
UPDATE stations SET score = 54, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJBDB-KUA'; -- measured
UPDATE stations SET score = 43, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJBDB-PAN';
UPDATE stations SET score = 43, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJBDB-RAS';
UPDATE stations SET score = 43, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJBDB-SET';
UPDATE stations SET score = 26, updatedAt = CURRENT_TIMESTAMP WHERE id = 'LRTJBDB-TMI';
UPDATE stations SET score = 54, updatedAt = CURRENT_TIMESTAMP WHERE id = 'MRTJ-BHI'; -- measured
UPDATE stations SET score = 35, updatedAt = CURRENT_TIMESTAMP WHERE id = 'MRTJ-BLA';
UPDATE stations SET score = 56, updatedAt = CURRENT_TIMESTAMP WHERE id = 'MRTJ-BLM'; -- measured
UPDATE stations SET score = 35, updatedAt = CURRENT_TIMESTAMP WHERE id = 'MRTJ-BNH';
UPDATE stations SET score = 35, updatedAt = CURRENT_TIMESTAMP WHERE id = 'MRTJ-CPR';
UPDATE stations SET score = 62, updatedAt = CURRENT_TIMESTAMP WHERE id = 'MRTJ-DKA'; -- measured
UPDATE stations SET score = 35, updatedAt = CURRENT_TIMESTAMP WHERE id = 'MRTJ-FTM';
UPDATE stations SET score = 35, updatedAt = CURRENT_TIMESTAMP WHERE id = 'MRTJ-HJN';
UPDATE stations SET score = 50, updatedAt = CURRENT_TIMESTAMP WHERE id = 'MRTJ-IST'; -- measured
UPDATE stations SET score = 54, updatedAt = CURRENT_TIMESTAMP WHERE id = 'MRTJ-LBB'; -- measured
UPDATE stations SET score = 35, updatedAt = CURRENT_TIMESTAMP WHERE id = 'MRTJ-SNY';
UPDATE stations SET score = 52, updatedAt = CURRENT_TIMESTAMP WHERE id = 'MRTJ-SSM';
UPDATE stations SET score = 35, updatedAt = CURRENT_TIMESTAMP WHERE id = 'MRTJ-STB';

UPDATE hubs SET score = 52, updatedAt = CURRENT_TIMESTAMP WHERE id = 'HUB-CSW';
UPDATE hubs SET score = 61, updatedAt = CURRENT_TIMESTAMP WHERE id = 'HUB-CW';
UPDATE hubs SET score = 79, updatedAt = CURRENT_TIMESTAMP WHERE id = 'HUB-DKA';
UPDATE hubs SET score = 62, updatedAt = CURRENT_TIMESTAMP WHERE id = 'HUB-SEN';
