UPDATE transfers SET dataType = 'INTERNAL', toStationId = 'TJ-H00047P', toStationData = NULL, distance = 310, updatedAt = CURRENT_TIMESTAMP WHERE id = 'T-KCI-SUD-XTJ1';
UPDATE transfers SET dataType = 'INTERNAL', toStationId = 'TJ-H00283P', toStationData = NULL, distance = 310, updatedAt = CURRENT_TIMESTAMP WHERE id = 'T-KCI-SUD-XTJ2';
UPDATE transfers SET dataType = 'INTERNAL', toStationId = 'TJ-B07663P', toStationData = NULL, distance = 70, updatedAt = CURRENT_TIMESTAMP WHERE id = 'T-KCI-SUD-XTJ3';
UPDATE transfers SET dataType = 'INTERNAL', toStationId = 'TJ-H00063S', toStationData = NULL, distance = distance, updatedAt = CURRENT_TIMESTAMP WHERE id = 'T-KCI-CW-XTJ1';
UPDATE transfers SET dataType = 'INTERNAL', toStationId = 'TJ-H00064S', toStationData = NULL, distance = distance, updatedAt = CURRENT_TIMESTAMP WHERE id = 'T-LRJTBDB-CKK-XTJ1';
UPDATE transfers SET dataType = 'INTERNAL', toStationId = 'TJ-H00276P', toStationData = NULL, distance = 170, updatedAt = CURRENT_TIMESTAMP WHERE id = 'T-LRTJBDB-CWG-XTJ1';
UPDATE transfers SET dataType = 'INTERNAL', toStationId = 'TJ-H00062S', toStationData = NULL, distance = distance, updatedAt = CURRENT_TIMESTAMP WHERE id = 'T-LRTJBDB-CIL-XTJ1';
UPDATE transfers SET dataType = 'INTERNAL', toStationId = 'TJ-H00198S', toStationData = NULL, distance = distance, updatedAt = CURRENT_TIMESTAMP WHERE id = 'T-LRTJBDB-PAN-XTJ1';
UPDATE transfers SET dataType = 'INTERNAL', toStationId = 'TJ-H00043P', toStationData = NULL, distance = 80, updatedAt = CURRENT_TIMESTAMP WHERE id = 'T-LRTJBDB-KUA-XTJ1';
UPDATE transfers SET dataType = 'INTERNAL', toStationId = 'TJ-H00069P', toStationData = NULL, distance = 80, updatedAt = CURRENT_TIMESTAMP WHERE id = 'T-LRTJBDB-RAS-XTJ1';
UPDATE transfers SET dataType = 'INTERNAL', toStationId = 'TJ-H00215P', toStationData = NULL, distance = distance, updatedAt = CURRENT_TIMESTAMP WHERE id = 'T-LRTJBDB-SET-XTJ1';
UPDATE transfers SET dataType = 'INTERNAL', toStationId = 'TJ-H00014P', toStationData = NULL, distance = 240, updatedAt = CURRENT_TIMESTAMP WHERE id = 'T-MRTJ-BLM-XTJ1';
UPDATE transfers SET distance = 550, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'KCI-PSE' AND toStationId = 'TJ-H00212P';
UPDATE transfers SET distance = 550, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00212P' AND toStationId = 'KCI-PSE';
UPDATE transfers SET distance = 650, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'KCI-PSE' AND toStationId = 'TJ-H00213P';
UPDATE transfers SET distance = 650, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00213P' AND toStationId = 'KCI-PSE';
UPDATE transfers SET distance = 60, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00212P' AND toStationId = 'TJ-H00213P';
UPDATE transfers SET distance = 60, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00213P' AND toStationId = 'TJ-H00212P';
UPDATE transfers SET distance = 630, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'KCI-PSE' AND toStationId = 'TJ-H00005P';
UPDATE transfers SET distance = 630, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00005P' AND toStationId = 'KCI-PSE';
UPDATE transfers SET distance = 385, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00005P' AND toStationId = 'TJ-H00213P';
UPDATE transfers SET distance = 385, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00213P' AND toStationId = 'TJ-H00005P';
UPDATE transfers SET distance = 430, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00005P' AND toStationId = 'TJ-H00212P';
UPDATE transfers SET distance = 430, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00212P' AND toStationId = 'TJ-H00005P';
UPDATE transfers SET distance = 110, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'KCI-JNG' AND toStationId = 'TJ-H00225P';
UPDATE transfers SET distance = 110, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00225P' AND toStationId = 'KCI-JNG';
UPDATE transfers SET distance = 300, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00225P' AND toStationId = 'TJ-H00148P';
UPDATE transfers SET distance = 300, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00148P' AND toStationId = 'TJ-H00225P';
UPDATE transfers SET distance = 460, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'KCI-JNG' AND toStationId = 'TJ-H00148P';
UPDATE transfers SET distance = 460, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00148P' AND toStationId = 'KCI-JNG';
UPDATE transfers SET distance = 490, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'KCI-KBY' AND toStationId = 'TJ-H00257P';
UPDATE transfers SET distance = 490, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00257P' AND toStationId = 'KCI-KBY';
UPDATE transfers SET distance = 250, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'KCI-KBY' AND toStationId = 'TJ-H00149P';
UPDATE transfers SET distance = 250, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00149P' AND toStationId = 'KCI-KBY';
UPDATE transfers SET distance = 320, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00149P' AND toStationId = 'TJ-H00257P';
UPDATE transfers SET distance = 320, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00257P' AND toStationId = 'TJ-H00149P';
UPDATE transfers SET distance = 200, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'MRTJ-SSM' AND toStationId = 'TJ-H00041P';
UPDATE transfers SET distance = 200, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00041P' AND toStationId = 'MRTJ-SSM';
UPDATE transfers SET distance = 130, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'MRTJ-SSM' AND toStationId = 'TJ-H00265P';
UPDATE transfers SET distance = 130, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00265P' AND toStationId = 'MRTJ-SSM';
UPDATE transfers SET distance = 150, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'MRTJ-SSM' AND toStationId = 'TJ-H00266P';
UPDATE transfers SET distance = 150, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00266P' AND toStationId = 'MRTJ-SSM';
UPDATE transfers SET distance = 110, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00266P' AND toStationId = 'TJ-H00265P';
UPDATE transfers SET distance = 110, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00265P' AND toStationId = 'TJ-H00266P';
UPDATE transfers SET distance = 200, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00266P' AND toStationId = 'TJ-H00041P';
UPDATE transfers SET distance = 200, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00041P' AND toStationId = 'TJ-H00266P';
UPDATE transfers SET distance = 200, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00265P' AND toStationId = 'TJ-H00041P';
UPDATE transfers SET distance = 200, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00041P' AND toStationId = 'TJ-H00265P';
UPDATE transfers SET distance = 310, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'LRTJBDB-KAM' AND toStationId = 'TJ-H00096P';
UPDATE transfers SET distance = 310, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00096P' AND toStationId = 'LRTJBDB-KAM';
UPDATE transfers SET distance = 180, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'MRTJ-BHI' AND toStationId = 'TJ-H00022P';
UPDATE transfers SET distance = 180, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00022P' AND toStationId = 'MRTJ-BHI';
UPDATE transfers SET distance = 330, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'LRTJBDB-TMI' AND toStationId = 'TJ-H00060P';
UPDATE transfers SET distance = 330, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00060P' AND toStationId = 'LRTJBDB-TMI';
UPDATE transfers SET distance = 150, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'KCI-JUA' AND toStationId = 'TJ-H00092P';
UPDATE transfers SET distance = 150, updatedAt = CURRENT_TIMESTAMP WHERE dataType = 'INTERNAL' AND fromStationId = 'TJ-H00092P' AND toStationId = 'KCI-JUA';
