package id.shiorilabs.commute.core.constants

// GENERATED by `pnpm --filter @commute/api android:constants` from AMENITY_TYPES in
// apps/constants/src/index.ts. Edit it there and rerun; changes here are overwritten.

/**
 * A station facility's label by its API type (`TOILET` → "Toilet"). The API adds types without
 * notice, so a lookup can miss: fall back to the type itself.
 */
val AMENITY_LABELS: Map<String, String> = mapOf(
    "TOILET" to "Toilet",
    "TOILET_ACCESSIBLE" to "Toilet Difabel",
    "PARKING" to "Parkir",
    "BIKE_PARKING" to "Parkir Sepeda",
    "WIFI" to "WiFi",
    "CHARGING_STATION" to "Charging Station",
    "PRAYING_ROOM" to "Mushola",
    "ESCALATOR_UNPAID" to "Eskalator (Area Umum)",
    "ESCALATOR_PAID" to "Eskalator (Area Berbayar)",
    "ELEVATOR_UNPAID" to "Lift (Area Umum)",
    "ELEVATOR_PAID" to "Lift (Area Berbayar)",
    "LOCKERS" to "Loker",
    "NURSING_ROOM" to "Ruang Menyusui",
)
