package id.shiorilabs.commute.core.constants

// GENERATED by `pnpm --filter @commute/api android:constants` from HOLIDAYS in
// apps/constants/src/index.ts. Edit it there and rerun; changes here are overwritten.

/**
 * Indonesian national holidays, as local `YYYY-MM-DD`. Holidays run a Sunday-shaped service, so
 * the service day of a date in here is SUN.
 */
val HOLIDAYS: Set<String> = setOf(
    "2026-01-01",
    "2026-01-17",
    "2026-02-17",
    "2026-03-19",
    "2026-03-20",
    "2026-03-21",
    "2026-04-03",
    "2026-05-01",
    "2026-05-14",
    "2026-05-27",
    "2026-05-31",
    "2026-06-01",
    "2026-06-16",
    "2026-08-17",
    "2026-08-25",
    "2026-12-25",
)
