package id.shiorilabs.commute.core.constants

// GENERATED by `pnpm --filter @commute/api android:constants` from OPERATORS in
// apps/constants/src/index.ts. Edit it there and rerun; changes here are overwritten.

/**
 * An operator's name by its API code (`KCI` → "Commuter Line"). The API adds operators without
 * notice, so a lookup can miss: fall back to the code itself.
 */
val OPERATOR_NAMES: Map<String, String> = mapOf(
    "KCI" to "Commuter Line",
    "MRTJ" to "MRT Jakarta",
    "LRTJ" to "LRT Jakarta",
    "LRTJBDB" to "LRT Jabodebek",
    "TJ" to "TransJakarta",
    "APCGK" to "Kalayang Bandara",
)
