// GENERATED by src/db/scripts/generateDataPlatformNetwork.ts — do not edit by hand.
// Baked Jabodetabek rail topology (KRL/MRT/LRT) for the hero network canvas.
// Layout is FDTJ schematic space (sx/sy); lng/lat kept for reference only.
// Re-generate: cd apps/api && npm run generate:dataplatform-network

export interface NetNode {
  id: string
  name: string
  lng: number
  lat: number
  sx: number
  sy: number
  col: number
  row: number
  interchange: boolean
}

export interface NetLine {
  code: string
  operator: string
  name: string
  color: string
  segments: string[][]
}

export interface Network {
  nodes: NetNode[]
  lines: NetLine[]
  bounds: { minLng: number, maxLng: number, minLat: number, maxLat: number }
  schematicBounds: { minX: number, maxX: number, minY: number, maxY: number }
  grid: { cols: number, rows: number }
}

export const NETWORK: Network = {
  nodes: [
    {
      id: 'KCI-CKR',
      name: 'Cikarang',
      lng: 107.1452,
      lat: -6.2552,
      sx: 8295.927127410796,
      sy: 4140.609011099432,
      col: 117,
      row: 39,
      interchange: false
    },
    {
      id: 'KCI-TLM',
      name: 'Metland Telagamurni',
      lng: 107.1111,
      lat: -6.2572,
      sx: 8199.223413046771,
      sy: 4120.142249659238,
      col: 116,
      row: 38,
      interchange: false
    },
    {
      id: 'KCI-CIT',
      name: 'Cibitung',
      lng: 107.0836,
      lat: -6.2617,
      sx: 8101.928958507043,
      sy: 4119.528008549615,
      col: 114,
      row: 38,
      interchange: false
    },
    {
      id: 'KCI-TB',
      name: 'Tambun',
      lng: 107.0557,
      lat: -6.2586,
      sx: 8003.943228894328,
      sy: 4119.205257030952,
      col: 113,
      row: 38,
      interchange: false
    },
    {
      id: 'KCI-BKST',
      name: 'Bekasi Timur',
      lng: 107.0181,
      lat: -6.2468,
      sx: 7907.342983706277,
      sy: 4119.471931217503,
      col: 111,
      row: 38,
      interchange: false
    },
    {
      id: 'KCI-BKS',
      name: 'Bekasi',
      lng: 106.9991,
      lat: -6.2364,
      sx: 7810.34275854696,
      sy: 4120.138604138595,
      col: 110,
      row: 38,
      interchange: false
    },
    {
      id: 'KCI-KRI',
      name: 'Kranji',
      lng: 106.9798,
      lat: -6.2244,
      sx: 7712.780902071809,
      sy: 4120.079656672218,
      col: 109,
      row: 38,
      interchange: false
    },
    {
      id: 'KCI-CUK',
      name: 'Cakung',
      lng: 106.9523,
      lat: -6.2189,
      sx: 7594.2472941764845,
      sy: 4119.74632959331,
      col: 107,
      row: 38,
      interchange: false
    },
    {
      id: 'KCI-KLDB',
      name: 'Klender Baru',
      lng: 106.9401,
      lat: -6.2176,
      sx: 7475.980358885888,
      sy: 4120.74632959331,
      col: 105,
      row: 38,
      interchange: false
    },
    {
      id: 'KCI-BUA',
      name: 'Buaran',
      lng: 106.9232,
      lat: -6.2154,
      sx: 7223.7459984553025,
      sy: 4119.385689107112,
      col: 102,
      row: 38,
      interchange: false
    },
    {
      id: 'KCI-KLD',
      name: 'Klender',
      lng: 106.8994,
      lat: -6.2133,
      sx: 6761.4432068562355,
      sy: 4119.417867830969,
      col: 95,
      row: 38,
      interchange: false
    },
    {
      id: 'KCI-JNG',
      name: 'Jatinegara',
      lng: 106.8702,
      lat: -6.2149,
      sx: 5985.446268073702,
      sy: 4119.887766850177,
      col: 84,
      row: 38,
      interchange: false
    },
    {
      id: 'KCI-POK',
      name: 'Pondok Jati',
      lng: 106.8623,
      lat: -6.2091,
      sx: 5847.203633721686,
      sy: 3859.684357016286,
      col: 82,
      row: 35,
      interchange: false
    },
    {
      id: 'KCI-KMT',
      name: 'Kramat',
      lng: 106.8565,
      lat: -6.1936,
      sx: 5710.2970150840965,
      sy: 3547.4622929992474,
      col: 80,
      row: 30,
      interchange: false
    },
    {
      id: 'KCI-GST',
      name: 'Gang Sentiong',
      lng: 106.8507,
      lat: -6.186,
      sx: 5509.250665940374,
      sy: 3345.7492673419215,
      col: 77,
      row: 28,
      interchange: false
    },
    {
      id: 'KCI-PSE',
      name: 'Pasar Senen',
      lng: 106.8443,
      lat: -6.1746,
      sx: 5306.8663219165455,
      sy: 3081.9823636256324,
      col: 74,
      row: 24,
      interchange: false
    },
    {
      id: 'KCI-KMO',
      name: 'Kemayoran',
      lng: 106.8415,
      lat: -6.1616,
      sx: 5306.696511141978,
      sy: 2769.7425222192364,
      col: 74,
      row: 20,
      interchange: false
    },
    {
      id: 'KCI-RJW',
      name: 'Rajawali',
      lng: 106.8367,
      lat: -6.1448,
      sx: 5305.5968833666075,
      sy: 2418.6775400070596,
      col: 74,
      row: 15,
      interchange: false
    },
    {
      id: 'KCI-KPB',
      name: 'Kampung Bandan',
      lng: 106.8285,
      lat: -6.1325,
      sx: 4816.783688606127,
      sy: 1804.1314770000565,
      col: 67,
      row: 6,
      interchange: true
    },
    {
      id: 'KCI-AK',
      name: 'Angke',
      lng: 106.8008,
      lat: -6.1446,
      sx: 2958.6360682902045,
      sy: 2169.788770145613,
      col: 41,
      row: 11,
      interchange: false
    },
    {
      id: 'KCI-DU',
      name: 'Duri',
      lng: 106.8013,
      lat: -6.1552,
      sx: 2917.5520215974793,
      sy: 2544.802464714043,
      col: 40,
      row: 17,
      interchange: true
    },
    {
      id: 'KCI-THB',
      name: 'Tanah Abang',
      lng: 106.8107,
      lat: -6.1857,
      sx: 2917.491827365562,
      sy: 3273.9308340286652,
      col: 40,
      row: 27,
      interchange: true
    },
    {
      id: 'KCI-KAT',
      name: 'Karet',
      lng: 106.8159,
      lat: -6.2007,
      sx: 3225.1179441597874,
      sy: 3667.6168821005904,
      col: 45,
      row: 32,
      interchange: false
    },
    {
      id: 'KCI-SUDB',
      name: 'Sudirman Baru',
      lng: 106.8196,
      lat: -6.2015,
      sx: 3584.6166900140834,
      sy: 3698.1854122611257,
      col: 50,
      row: 32,
      interchange: true
    },
    {
      id: 'KCI-SUD',
      name: 'Sudirman',
      lng: 106.8237,
      lat: -6.2024,
      sx: 3835.558899715026,
      sy: 3671.917890875361,
      col: 53,
      row: 32,
      interchange: true
    },
    {
      id: 'KCI-MRI',
      name: 'Manggarai',
      lng: 106.8498,
      lat: -6.21,
      sx: 4867.700340100056,
      sy: 3863.169655453152,
      col: 68,
      row: 35,
      interchange: true
    },
    {
      id: 'KCI-MTR',
      name: 'Matraman',
      lng: 106.8597,
      lat: -6.2125,
      sx: 5662.331122190524,
      sy: 4121.621720324027,
      col: 79,
      row: 38,
      interchange: false
    },
    {
      id: 'KCI-JAKK',
      name: 'Jakarta Kota',
      lng: 106.8146,
      lat: -6.1375,
      sx: 3909.454805483811,
      sy: 1802.6403197994955,
      col: 54,
      row: 6,
      interchange: true
    },
    {
      id: 'KCI-JAY',
      name: 'Jayakarta',
      lng: 106.8229,
      lat: -6.1411,
      sx: 4325.335030085292,
      sy: 2032.0097665968506,
      col: 60,
      row: 9,
      interchange: false
    },
    {
      id: 'KCI-MGB',
      name: 'Mangga Besar',
      lng: 106.8269,
      lat: -6.1498,
      sx: 4325.868450999741,
      sy: 2215.375644933237,
      col: 60,
      row: 12,
      interchange: false
    },
    {
      id: 'KCI-SW',
      name: 'Sawah Besar',
      lng: 106.8276,
      lat: -6.1606,
      sx: 4325.87636612151,
      sy: 2412.6087398906893,
      col: 60,
      row: 15,
      interchange: false
    },
    {
      id: 'KCI-JUA',
      name: 'Juanda',
      lng: 106.8304,
      lat: -6.1667,
      sx: 4325.811190127875,
      sy: 2644.393816429351,
      col: 60,
      row: 18,
      interchange: false
    },
    {
      id: 'KCI-GDD',
      name: 'Gondangdia',
      lng: 106.8324,
      lat: -6.1859,
      sx: 4450.500372423383,
      sy: 3391.208322984253,
      col: 62,
      row: 28,
      interchange: false
    },
    {
      id: 'KCI-CKI',
      name: 'Cikini',
      lng: 106.8412,
      lat: -6.1984,
      sx: 4604.63436836683,
      sy: 3543.7422958577617,
      col: 64,
      row: 30,
      interchange: false
    },
    {
      id: 'KCI-TEB',
      name: 'Tebet',
      lng: 106.8584,
      lat: -6.2262,
      sx: 5279.706444405642,
      sy: 4431.059153936346,
      col: 74,
      row: 43,
      interchange: false
    },
    {
      id: 'KCI-CW',
      name: 'Cawang',
      lng: 106.8586,
      lat: -6.2424,
      sx: 5279.706444405642,
      sy: 4717.460050987828,
      col: 74,
      row: 47,
      interchange: true
    },
    {
      id: 'KCI-DRN',
      name: 'Duren Kalibata',
      lng: 106.8551,
      lat: -6.2552,
      sx: 5279.323931218156,
      sy: 5134.839900296753,
      col: 74,
      row: 52,
      interchange: false
    },
    {
      id: 'KCI-PSMB',
      name: 'Pasar Minggu Baru',
      lng: 106.8516,
      lat: -6.2629,
      sx: 5279.7906043978455,
      sy: 5368.37391365695,
      col: 74,
      row: 56,
      interchange: false
    },
    {
      id: 'KCI-PSM',
      name: 'Pasar Minggu',
      lng: 106.8445,
      lat: -6.284,
      sx: 5280.421242059746,
      sy: 5602.176544531337,
      col: 74,
      row: 59,
      interchange: false
    },
    {
      id: 'KCI-TNT',
      name: 'Tanjung Barat',
      lng: 106.8389,
      lat: -6.3078,
      sx: 5280.168057911076,
      sy: 5837.413595910363,
      col: 74,
      row: 62,
      interchange: false
    },
    {
      id: 'KCI-LNA',
      name: 'Lenteng Agung',
      lng: 106.8347,
      lat: -6.3303,
      sx: 5280.168057911076,
      sy: 5983.013994782389,
      col: 74,
      row: 64,
      interchange: false
    },
    {
      id: 'KCI-UP',
      name: 'Univ. Pancasila',
      lng: 106.8343,
      lat: -6.3389,
      sx: 5280.396974307193,
      sy: 6084.888587276785,
      col: 74,
      row: 65,
      interchange: false
    },
    {
      id: 'KCI-UI',
      name: 'Univ. Indonesia',
      lng: 106.8317,
      lat: -6.3607,
      sx: 5279.825068933635,
      sy: 6196.022260564108,
      col: 74,
      row: 67,
      interchange: false
    },
    {
      id: 'KCI-POC',
      name: 'Pondok Cina',
      lng: 106.8323,
      lat: -6.3687,
      sx: 5280.291742317517,
      sy: 6293.622496161289,
      col: 74,
      row: 68,
      interchange: false
    },
    {
      id: 'KCI-DPB',
      name: 'Depok Baru',
      lng: 106.8216,
      lat: -6.3912,
      sx: 5279.825068933635,
      sy: 6401.356140915768,
      col: 74,
      row: 70,
      interchange: false
    },
    {
      id: 'KCI-DP',
      name: 'Depok',
      lng: 106.817,
      lat: -6.4047,
      sx: 5386.876545774022,
      sy: 6556.725190506687,
      col: 76,
      row: 72,
      interchange: false
    },
    {
      id: 'KCI-CTA',
      name: 'Citayam',
      lng: 106.8024,
      lat: -6.4488,
      sx: 5535.505815161017,
      sy: 6557.336401380784,
      col: 78,
      row: 72,
      interchange: false
    },
    {
      id: 'KCI-BJD',
      name: 'Bojonggede',
      lng: 106.7951,
      lat: -6.4927,
      sx: 5809.065559989924,
      sy: 6556.73628757124,
      col: 82,
      row: 72,
      interchange: false
    },
    {
      id: 'KCI-CLT',
      name: 'Cilebut',
      lng: 106.8005,
      lat: -6.5308,
      sx: 6022.929374749703,
      sy: 6557.202929865587,
      col: 85,
      row: 72,
      interchange: false
    },
    {
      id: 'KCI-BOO',
      name: 'Bogor',
      lng: 106.7904,
      lat: -6.5956,
      sx: 6236.409183932918,
      sy: 6556.869759086437,
      col: 88,
      row: 72,
      interchange: false
    },
    {
      id: 'KCI-PDRG',
      name: 'Pondok Rajeg',
      lng: 106.8242,
      lat: -6.4607,
      sx: 5808.982923272141,
      sy: 6333.78936877742,
      col: 82,
      row: 69,
      interchange: false
    },
    {
      id: 'KCI-CBN',
      name: 'Cibinong',
      lng: 106.8526,
      lat: -6.464,
      sx: 5946.191400462006,
      sy: 6333.655917608516,
      col: 83,
      row: 69,
      interchange: false
    },
    {
      id: 'KCI-NMO',
      name: 'Nambo',
      lng: 106.9062,
      lat: -6.4662,
      sx: 6092.867007608768,
      sy: 6332.78936877742,
      col: 86,
      row: 69,
      interchange: false
    },
    {
      id: 'KCI-PLM',
      name: 'Palmerah',
      lng: 106.7973,
      lat: -6.2075,
      sx: 2596.2571281558967,
      sy: 4100.399403223949,
      col: 36,
      row: 38,
      interchange: false
    },
    {
      id: 'KCI-KBY',
      name: 'Kebayoran',
      lng: 106.7824,
      lat: -6.2372,
      sx: 2440.284136069208,
      sy: 4711.693811103827,
      col: 33,
      row: 46,
      interchange: false
    },
    {
      id: 'KCI-PDJ',
      name: 'Pondok Ranji',
      lng: 106.7445,
      lat: -6.2765,
      sx: 2185.703098235334,
      sy: 5154.215104334653,
      col: 30,
      row: 53,
      interchange: false
    },
    {
      id: 'KCI-JMU',
      name: 'Jurang Mangu',
      lng: 106.729,
      lat: -6.2887,
      sx: 2097.6360344646655,
      sy: 5242.282188450468,
      col: 29,
      row: 54,
      interchange: false
    },
    {
      id: 'KCI-SDM',
      name: 'Sudimara',
      lng: 106.7126,
      lat: -6.2969,
      sx: 1996.3022104734755,
      sy: 5344.082664425907,
      col: 27,
      row: 55,
      interchange: false
    },
    {
      id: 'KCI-RU',
      name: 'Rawa Buntu',
      lng: 106.6762,
      lat: -6.3149,
      sx: 1854.6721146590958,
      sy: 5414.981740684252,
      col: 25,
      row: 56,
      interchange: false
    },
    {
      id: 'KCI-SRP',
      name: 'Serpong',
      lng: 106.6653,
      lat: -6.32,
      sx: 1737.1382300392288,
      sy: 5415.115132747257,
      col: 23,
      row: 56,
      interchange: false
    },
    {
      id: 'KCI-CSK',
      name: 'Cisauk',
      lng: 106.6412,
      lat: -6.3244,
      sx: 1619.8043724784302,
      sy: 5415.048416370608,
      col: 22,
      row: 56,
      interchange: false
    },
    {
      id: 'KCI-CC',
      name: 'Cicayur',
      lng: 106.6186,
      lat: -6.3295,
      sx: 1502.9465853151876,
      sy: 5415.115112402111,
      col: 20,
      row: 56,
      interchange: false
    },
    {
      id: 'KCI-JTK',
      name: 'Jatake',
      lng: 106.6067,
      lat: -6.3346,
      sx: 1386.3956983841724,
      sy: 5414.7505832577035,
      col: 18,
      row: 56,
      interchange: false
    },
    {
      id: 'KCI-PRP',
      name: 'Parung Panjang',
      lng: 106.5699,
      lat: -6.3442,
      sx: 1269.1951718509395,
      sy: 5414.7505832577035,
      col: 17,
      row: 56,
      interchange: false
    },
    {
      id: 'KCI-CJT',
      name: 'Cilejit',
      lng: 106.5095,
      lat: -6.3543,
      sx: 1152.1531886602666,
      sy: 5415.1720765398295,
      col: 15,
      row: 56,
      interchange: false
    },
    {
      id: 'KCI-DAR',
      name: 'Daru',
      lng: 106.4924,
      lat: -6.338,
      sx: 1035.415111961892,
      sy: 5415.472772960553,
      col: 13,
      row: 56,
      interchange: false
    },
    {
      id: 'KCI-TEJ',
      name: 'Tenjo',
      lng: 106.4615,
      lat: -6.3274,
      sx: 918.1479019345113,
      sy: 5415.006141263936,
      col: 12,
      row: 56,
      interchange: false
    },
    {
      id: 'KCI-TGS',
      name: 'Tigaraksa',
      lng: 106.434,
      lat: -6.3289,
      sx: 802.0301662007822,
      sy: 5414.947279965503,
      col: 10,
      row: 56,
      interchange: false
    },
    {
      id: 'KCI-CKY',
      name: 'Cikoya',
      lng: 106.4115,
      lat: -6.3356,
      sx: 684.1629733341169,
      sy: 5414.28060120974,
      col: 8,
      row: 56,
      interchange: false
    },
    {
      id: 'KCI-MJ',
      name: 'Maja',
      lng: 106.3965,
      lat: -6.3322,
      sx: 567.4291316101197,
      sy: 5414.947279965503,
      col: 7,
      row: 56,
      interchange: false
    },
    {
      id: 'KCI-CTR',
      name: 'Citeras',
      lng: 106.3324,
      lat: -6.3347,
      sx: 450.66881145956955,
      sy: 5415.473978540259,
      col: 5,
      row: 56,
      interchange: false
    },
    {
      id: 'KCI-RK',
      name: 'Rangkasbitung',
      lng: 106.2512,
      lat: -6.3527,
      sx: 333.6349579707857,
      sy: 5394.707203720345,
      col: 3,
      row: 56,
      interchange: false
    },
    {
      id: 'KCI-GGL',
      name: 'Grogol',
      lng: 106.7887,
      lat: -6.162,
      sx: 2413.805428439529,
      sy: 2475.2653470336454,
      col: 33,
      row: 16,
      interchange: false
    },
    {
      id: 'KCI-PSG',
      name: 'Pesing',
      lng: 106.7718,
      lat: -6.1612,
      sx: 2172.9719088598663,
      sy: 2643.4894832333935,
      col: 30,
      row: 18,
      interchange: false
    },
    {
      id: 'KCI-TKO',
      name: 'Taman Kota',
      lng: 106.7562,
      lat: -6.1585,
      sx: 1799.4691051090472,
      sy: 2871.137389649867,
      col: 24,
      row: 21,
      interchange: false
    },
    {
      id: 'KCI-BOI',
      name: 'Bojong Indah',
      lng: 106.7363,
      lat: -6.16,
      sx: 1581.7344382215902,
      sy: 2871.0707125591175,
      col: 21,
      row: 21,
      interchange: false
    },
    {
      id: 'KCI-RW',
      name: 'Rawa Buaya',
      lng: 106.7235,
      lat: -6.1626,
      sx: 1357.4976363745518,
      sy: 2849.704919258246,
      col: 18,
      row: 21,
      interchange: false
    },
    {
      id: 'KCI-KDS',
      name: 'Kalideres',
      lng: 106.7035,
      lat: -6.1661,
      sx: 1140.4603772104954,
      sy: 2871.469112748751,
      col: 15,
      row: 21,
      interchange: false
    },
    {
      id: 'KCI-PI',
      name: 'Poris',
      lng: 106.681,
      lat: -6.1697,
      sx: 896.7112047161678,
      sy: 2871.1745049467213,
      col: 11,
      row: 21,
      interchange: false
    },
    {
      id: 'KCI-BPR',
      name: 'Batu Ceper',
      lng: 106.6648,
      lat: -6.1721,
      sx: 675.8430748095072,
      sy: 2848.974330304555,
      col: 8,
      row: 21,
      interchange: false
    },
    {
      id: 'KCI-TTI',
      name: 'Tanah Tinggi',
      lng: 106.6459,
      lat: -6.1752,
      sx: 452.8696372723934,
      sy: 2870.846283599212,
      col: 5,
      row: 21,
      interchange: false
    },
    {
      id: 'KCI-TNG',
      name: 'Tangerang',
      lng: 106.631,
      lat: -6.1768,
      sx: 232.46819392907653,
      sy: 2871.246256822204,
      col: 2,
      row: 21,
      interchange: false
    },
    {
      id: 'KCI-AC',
      name: 'Ancol',
      lng: 106.8451,
      lat: -6.128,
      sx: 5473.852396352422,
      sy: 1779.109675683061,
      col: 77,
      row: 6,
      interchange: false
    },
    {
      id: 'KCI-JIS',
      name: 'Jakarta International Stadium',
      lng: 106.862,
      lat: -6.1225,
      sx: 5920.309751137363,
      sy: 1776.9832539038212,
      col: 83,
      row: 6,
      interchange: false
    },
    {
      id: 'KCI-TPK',
      name: 'Tanjung Priok',
      lng: 106.8811,
      lat: -6.1109,
      sx: 6064.382586653755,
      sy: 1494.4892706951366,
      col: 85,
      row: 2,
      interchange: false
    },
    {
      id: 'MRTJ-LBB',
      name: 'Lebak Bulus',
      lng: 106.7749,
      lat: -6.2892,
      sx: 2544.5534481340537,
      sy: 5856.340612249267,
      col: 35,
      row: 62,
      interchange: false
    },
    {
      id: 'MRTJ-FTM',
      name: 'Fatmawati Indomaret',
      lng: 106.7924,
      lat: -6.2924,
      sx: 2990.2882426168467,
      sy: 5857.407272648028,
      col: 41,
      row: 62,
      interchange: false
    },
    {
      id: 'MRTJ-CPR',
      name: 'Cipete Raya',
      lng: 106.7973,
      lat: -6.2782,
      sx: 3169.555615010054,
      sy: 5637.073092800105,
      col: 44,
      row: 59,
      interchange: false
    },
    {
      id: 'MRTJ-HJN',
      name: 'Haji Nawi',
      lng: 106.7972,
      lat: -6.2666,
      sx: 3169.7402617549255,
      sy: 5414.15671870825,
      col: 44,
      row: 56,
      interchange: false
    },
    {
      id: 'MRTJ-BLA',
      name: 'Blok A',
      lng: 106.797,
      lat: -6.2557,
      sx: 3169.8069162250767,
      sy: 5193.743823376239,
      col: 44,
      row: 53,
      interchange: false
    },
    {
      id: 'MRTJ-BLM',
      name: 'Blok M BCA',
      lng: 106.7981,
      lat: -6.2444,
      sx: 3169.7402617549255,
      sy: 5020.543156395224,
      col: 44,
      row: 51,
      interchange: false
    },
    {
      id: 'MRTJ-SSM',
      name: 'Asean',
      lng: 106.7983,
      lat: -6.2387,
      sx: 3169.9988171085447,
      sy: 4878.886767727487,
      col: 44,
      row: 49,
      interchange: false
    },
    {
      id: 'MRTJ-SNY',
      name: 'Senayan Mastercard',
      lng: 106.8024,
      lat: -6.2267,
      sx: 3217.044915292122,
      sy: 4431.802492159645,
      col: 45,
      row: 43,
      interchange: false
    },
    {
      id: 'MRTJ-IST',
      name: 'Istora Mandiri',
      lng: 106.8085,
      lat: -6.2222,
      sx: 3367.5121727815554,
      sy: 4280.801907423224,
      col: 47,
      row: 41,
      interchange: false
    },
    {
      id: 'MRTJ-BNH',
      name: 'Bendungan Hilir',
      lng: 106.8179,
      lat: -6.2149,
      sx: 3501.5143484044142,
      sy: 4152.090044695461,
      col: 49,
      row: 39,
      interchange: false
    },
    {
      id: 'MRTJ-STB',
      name: 'Setiabudi Astra',
      lng: 106.8215,
      lat: -6.2088,
      sx: 3595.333361553024,
      sy: 4052.1558207687976,
      col: 50,
      row: 37,
      interchange: false
    },
    {
      id: 'MRTJ-DKA',
      name: 'Dukuh Atas BNI',
      lng: 106.8227,
      lat: -6.2007,
      sx: 3631.747581051536,
      sy: 3596.0521920595997,
      col: 50,
      row: 31,
      interchange: true
    },
    {
      id: 'MRTJ-BHI',
      name: 'Bundaran HI Bank DKI',
      lng: 106.8229,
      lat: -6.1918,
      sx: 3635.36081619927,
      sy: 3493.8723452556296,
      col: 51,
      row: 30,
      interchange: false
    },
    {
      id: 'LRTJ-PGD',
      name: 'Pegangsaan Dua',
      lng: 106.9141,
      lat: -6.156,
      sx: 7276.252539584679,
      sy: 2405.6106777226687,
      col: 102,
      row: 15,
      interchange: false
    },
    {
      id: 'LRTJ-BVU',
      name: 'Boulevard Utara Summarecon Mall',
      lng: 106.906,
      lat: -6.1593,
      sx: 7092.2519166790225,
      sy: 2623.986748465909,
      col: 100,
      row: 18,
      interchange: false
    },
    {
      id: 'LRTJ-BVS',
      name: 'Boulevard Selatan',
      lng: 106.8999,
      lat: -6.1689,
      sx: 7092.2066922474805,
      sy: 2862.7690166057464,
      col: 100,
      row: 21,
      interchange: false
    },
    {
      id: 'LRTJ-PUM',
      name: 'Pulomas',
      lng: 106.8933,
      lat: -6.1772,
      sx: 7092.417341047522,
      sy: 3286.907005783305,
      col: 100,
      row: 27,
      interchange: false
    },
    {
      id: 'LRTJ-EQS',
      name: 'Equestrian',
      lng: 106.8912,
      lat: -6.1836,
      sx: 7091.884014046714,
      sy: 3438.9741947042817,
      col: 100,
      row: 29,
      interchange: false
    },
    {
      id: 'LRTJ-VEL',
      name: 'Velodrome',
      lng: 106.8911,
      lat: -6.1924,
      sx: 7092.350687045905,
      sy: 3586.2413592374965,
      col: 100,
      row: 31,
      interchange: false
    },
    {
      id: 'LRTJBDB-DKA',
      name: 'Dukuh Atas',
      lng: 106.8256,
      lat: -6.2047,
      sx: 3835.3879440387554,
      sy: 3871.541068789468,
      col: 53,
      row: 35,
      interchange: true
    },
    {
      id: 'LRTJBDB-SET',
      name: 'Setiabudi',
      lng: 106.8302,
      lat: -6.2092,
      sx: 4312.988147160663,
      sy: 4141.819441644214,
      col: 60,
      row: 39,
      interchange: true
    },
    {
      id: 'LRTJBDB-RAS',
      name: 'Rasuna Said',
      lng: 106.8321,
      lat: -6.2215,
      sx: 4313.839920273089,
      sy: 4425.382312677659,
      col: 60,
      row: 43,
      interchange: true
    },
    {
      id: 'LRTJBDB-KUA',
      name: 'Kuningan',
      lng: 106.8331,
      lat: -6.2287,
      sx: 4314.639931138376,
      sy: 4519.249301374852,
      col: 60,
      row: 44,
      interchange: true
    },
    {
      id: 'LRTJBDB-PAN',
      name: 'Pancoran',
      lng: 106.8383,
      lat: -6.2419,
      sx: 4686.332475925827,
      sy: 4828.6455622580825,
      col: 66,
      row: 48,
      interchange: true
    },
    {
      id: 'LRTJBDB-CKK',
      name: 'Cikoko',
      lng: 106.8569,
      lat: -6.2434,
      sx: 5340.600255496849,
      sy: 4827.495459900172,
      col: 75,
      row: 48,
      interchange: true
    },
    {
      id: 'LRTJBDB-CIL',
      name: 'Ciliwung',
      lng: 106.8638,
      lat: -6.2434,
      sx: 5608.77850652977,
      sy: 4827.279563288752,
      col: 79,
      row: 48,
      interchange: true
    },
    {
      id: 'LRTJBDB-CWG',
      name: 'Cawang',
      lng: 106.8712,
      lat: -6.2457,
      sx: 6078.1046053044665,
      sy: 4826.783995777422,
      col: 85,
      row: 48,
      interchange: true
    },
    {
      id: 'LRTJBDB-HAL',
      name: 'Halim',
      lng: 106.8874,
      lat: -6.2456,
      sx: 6879.613167774024,
      sy: 4809.0278808113335,
      col: 97,
      row: 48,
      interchange: false
    },
    {
      id: 'LRTJBDB-JBU',
      name: 'Jati Bening Baru',
      lng: 106.9282,
      lat: -6.2576,
      sx: 7713.68965211215,
      sy: 4808.198447142844,
      col: 109,
      row: 48,
      interchange: false
    },
    {
      id: 'LRTJBDB-CK1',
      name: 'Cikunir 1',
      lng: 106.9518,
      lat: -6.2564,
      sx: 7825.756602869294,
      sy: 4809.1984534785215,
      col: 110,
      row: 48,
      interchange: false
    },
    {
      id: 'LRTJBDB-CK2',
      name: 'Cikunir 2',
      lng: 106.9631,
      lat: -6.2546,
      sx: 7938.223500807091,
      sy: 4808.731820626328,
      col: 112,
      row: 48,
      interchange: false
    },
    {
      id: 'LRTJBDB-BEK',
      name: 'Bekasi Barat',
      lng: 106.9901,
      lat: -6.2528,
      sx: 8050.583010498817,
      sy: 4808.870088234224,
      col: 114,
      row: 48,
      interchange: false
    },
    {
      id: 'LRTJBDB-JTM',
      name: 'Jatimulya',
      lng: 107.0216,
      lat: -6.2638,
      sx: 8163.116602042026,
      sy: 4808.270088516306,
      col: 115,
      row: 48,
      interchange: false
    },
    {
      id: 'LRTJBDB-TMI',
      name: 'Tmii',
      lng: 106.8805,
      lat: -6.2928,
      sx: 6837.520542489227,
      sy: 5496.025652575524,
      col: 96,
      row: 57,
      interchange: false
    },
    {
      id: 'LRTJBDB-KAM',
      name: 'Kampung Rambutan',
      lng: 106.8843,
      lat: -6.3093,
      sx: 6837.587195256126,
      sy: 5763.159546245867,
      col: 96,
      row: 61,
      interchange: false
    },
    {
      id: 'LRTJBDB-CRC',
      name: 'Ciracas',
      lng: 106.8867,
      lat: -6.3237,
      sx: 6838.0538688726765,
      sy: 6007.430557875732,
      col: 96,
      row: 64,
      interchange: false
    },
    {
      id: 'LRTJBDB-HAR',
      name: 'Harjamukti',
      lng: 106.8955,
      lat: -6.3738,
      sx: 6837.689186171442,
      sy: 6252.6977646482055,
      col: 96,
      row: 68,
      interchange: false
    }
  ],
  lines: [
    {
      code: 'C',
      operator: 'KCI',
      name: 'Lin Cikarang',
      color: '#25B8EB',
      segments: [
        [
          'KCI-CKR',
          'KCI-TLM',
          'KCI-CIT',
          'KCI-TB',
          'KCI-BKST',
          'KCI-BKS',
          'KCI-KRI',
          'KCI-CUK',
          'KCI-KLDB',
          'KCI-BUA',
          'KCI-KLD',
          'KCI-JNG'
        ],
        [
          'KCI-JNG',
          'KCI-POK',
          'KCI-KMT',
          'KCI-GST',
          'KCI-PSE',
          'KCI-KMO',
          'KCI-RJW',
          'KCI-KPB',
          'KCI-AK',
          'KCI-DU',
          'KCI-THB',
          'KCI-KAT',
          'KCI-SUDB',
          'KCI-SUD',
          'KCI-MRI',
          'KCI-MTR'
        ],
        [
          'KCI-MTR',
          'KCI-JNG'
        ]
      ]
    },
    {
      code: 'B',
      operator: 'KCI',
      name: 'Lin Bogor',
      color: '#EE3D43',
      segments: [
        [
          'KCI-JAKK',
          'KCI-JAY',
          'KCI-MGB',
          'KCI-SW',
          'KCI-JUA',
          'KCI-GDD',
          'KCI-CKI',
          'KCI-MRI',
          'KCI-TEB',
          'KCI-CW',
          'KCI-DRN',
          'KCI-PSMB',
          'KCI-PSM',
          'KCI-TNT',
          'KCI-LNA',
          'KCI-UP',
          'KCI-UI',
          'KCI-POC',
          'KCI-DPB',
          'KCI-DP',
          'KCI-CTA'
        ],
        [
          'KCI-CTA',
          'KCI-BJD',
          'KCI-CLT',
          'KCI-BOO'
        ],
        [
          'KCI-CTA',
          'KCI-PDRG',
          'KCI-CBN',
          'KCI-NMO'
        ]
      ]
    },
    {
      code: 'R',
      operator: 'KCI',
      name: 'Lin Rangkasbitung',
      color: '#96C83E',
      segments: [
        [
          'KCI-THB',
          'KCI-PLM',
          'KCI-KBY',
          'KCI-PDJ',
          'KCI-JMU',
          'KCI-SDM',
          'KCI-RU',
          'KCI-SRP',
          'KCI-CSK',
          'KCI-CC',
          'KCI-JTK',
          'KCI-PRP',
          'KCI-CJT',
          'KCI-DAR',
          'KCI-TEJ',
          'KCI-TGS',
          'KCI-CKY',
          'KCI-MJ',
          'KCI-CTR',
          'KCI-RK'
        ]
      ]
    },
    {
      code: 'T',
      operator: 'KCI',
      name: 'Lin Tangerang',
      color: '#C15F28',
      segments: [
        [
          'KCI-DU',
          'KCI-GGL',
          'KCI-PSG',
          'KCI-TKO',
          'KCI-BOI',
          'KCI-RW',
          'KCI-KDS',
          'KCI-PI',
          'KCI-BPR',
          'KCI-TTI',
          'KCI-TNG'
        ]
      ]
    },
    {
      code: 'TP',
      operator: 'KCI',
      name: 'Lin Tanjung Priok',
      color: '#ED4F98',
      segments: [
        [
          'KCI-JAKK',
          'KCI-KPB',
          'KCI-AC',
          'KCI-JIS',
          'KCI-TPK'
        ]
      ]
    },
    {
      code: 'M',
      operator: 'MRTJ',
      name: 'Lin Utara Selatan',
      color: '#ca2a51',
      segments: [
        [
          'MRTJ-LBB',
          'MRTJ-FTM',
          'MRTJ-CPR',
          'MRTJ-HJN',
          'MRTJ-BLA',
          'MRTJ-BLM',
          'MRTJ-SSM',
          'MRTJ-SNY',
          'MRTJ-IST',
          'MRTJ-BNH',
          'MRTJ-STB',
          'MRTJ-DKA',
          'MRTJ-BHI'
        ]
      ]
    },
    {
      code: 'S',
      operator: 'LRTJ',
      name: 'Lin Selatan',
      color: '#F26324',
      segments: [
        [
          'LRTJ-PGD',
          'LRTJ-BVU',
          'LRTJ-BVS',
          'LRTJ-PUM',
          'LRTJ-EQS',
          'LRTJ-VEL'
        ]
      ]
    },
    {
      code: 'BK',
      operator: 'LRTJBDB',
      name: 'Lin Bekasi',
      color: '#006838',
      segments: [
        [
          'LRTJBDB-DKA',
          'LRTJBDB-SET',
          'LRTJBDB-RAS',
          'LRTJBDB-KUA',
          'LRTJBDB-PAN',
          'LRTJBDB-CKK',
          'LRTJBDB-CIL',
          'LRTJBDB-CWG',
          'LRTJBDB-HAL',
          'LRTJBDB-JBU',
          'LRTJBDB-CK1',
          'LRTJBDB-CK2',
          'LRTJBDB-BEK',
          'LRTJBDB-JTM'
        ]
      ]
    },
    {
      code: 'CB',
      operator: 'LRTJBDB',
      name: 'Lin Cibubur',
      color: '#21409A',
      segments: [
        [
          'LRTJBDB-DKA',
          'LRTJBDB-SET',
          'LRTJBDB-RAS',
          'LRTJBDB-KUA',
          'LRTJBDB-PAN',
          'LRTJBDB-CKK',
          'LRTJBDB-CIL',
          'LRTJBDB-CWG',
          'LRTJBDB-TMI',
          'LRTJBDB-KAM',
          'LRTJBDB-CRC',
          'LRTJBDB-HAR'
        ]
      ]
    }
  ],
  bounds: {
    minLng: 106.2512,
    maxLng: 107.1452,
    minLat: -6.5956,
    maxLat: -6.1109
  },
  schematicBounds: {
    minX: 232.46819392907653,
    maxX: 8295.927127410796,
    minY: 1494.4892706951366,
    maxY: 6557.336401380784
  },
  grid: {
    cols: 120,
    rows: 75
  }
}
