import * as fs from 'node:fs'
import * as path from 'node:path'
import { LINES } from './lines'

/*
 * Batch CSV -> SQL generator for the Kalayang Bandara timetables (source: the
 * FDTJ artwork prepared for InJourney Airports, `skytrain/`, dated 19 Feb 25 —
 * there is no public API for this service). Reads every
 * `<STATION>_<LINE>_<DEST>.csv` in ./timetables (one departure per line, H:MM or
 * HH:MM) and overwrites the committed `apcgk_<STATION>_<LINE>_<DEST>_timetable.sql`
 * files in db/scripts, so `git diff` is the transcription review. See
 * ./timetables/README.md for the workflow and the two known poster errors.
 */

const INPUT_DIR = path.join(__dirname, 'timetables')
const OUTPUT_DIR = path.resolve(__dirname, '../../db/scripts')

// boundFor uses the terminus's display name (stations.formattedName).
export const DEST_BOUND_FOR: Record<string, string> = {
  T1: 'Terminal 1',
  T3: 'Terminal 3'
}

const LINE_CODES = new Set<string>(LINES.map(line => line.lineCode))

/*
 * Trip-number series per direction. Mirrors the LRTJBDB convention: one series
 * per direction so the two never collide at the stations both pass through.
 * Towards T3 (airport-terminals-bound) takes the even 100s, towards T1 the odd.
 */
export const TRIP_NUMBER_BASE: Record<string, number> = {
  KLB_T3: 100,
  KLB_T1: 101
}

export interface TimetableFileKey {
  station: string
  line: string
  dest: string
}

export function parseTimetableFilename(basename: string): TimetableFileKey | { error: string } {
  const match = basename.match(/^([A-Z0-9]{2,4})_([A-Z]{2,3})_([A-Z0-9]{2,4})\.csv$/)
  if (!match?.[1] || !match[2] || !match[3]) {
    return { error: `"${basename}" does not match <STATION>_<LINE>_<DEST>.csv` }
  }

  const [, station, line, dest] = match
  if (!LINE_CODES.has(line)) {
    return { error: `"${basename}" has unknown line code "${line}" (expected ${[...LINE_CODES].join('/')})` }
  }
  if (!DEST_BOUND_FOR[dest]) {
    return { error: `"${basename}" has unknown destination "${dest}" (expected ${Object.keys(DEST_BOUND_FOR).join('/')})` }
  }
  if (station === dest) {
    return { error: `"${basename}" departs from its own destination` }
  }
  if (TRIP_NUMBER_BASE[`${line}_${dest}`] === undefined) {
    return { error: `"${basename}" pairs line ${line} with destination ${dest}, which is not a service pattern` }
  }

  return { station, line, dest }
}

/*
 * Zero-padding is load-bearing, not cosmetic: timetables sort lexically on
 * estimatedDeparture, so an unpadded '6:18:00' sorts after the 11pm departures.
 */
export function normalizeTime(raw: string): string | null {
  const match = raw.trim().match(/^([01]?\d|2[0-3]):([0-5]\d)$/)
  if (!match?.[1] || !match[2]) return null
  return `${match[1].padStart(2, '0')}:${match[2]}:00`
}

const esc = (value: string): string => value.replace(/'/g, '\'\'')

export function buildTimetableSQL(station: string, line: string, dest: string, times: string[]): string {
  const stationId = `APCGK-${station}`
  const boundFor = DEST_BOUND_FOR[dest]!
  const tripNumberBase = TRIP_NUMBER_BASE[`${line}_${dest}`]!

  const rows = times.map((time, index) => {
    const id = `${stationId}-${line}-${index + 1}-${dest}`
    const tripNumber = `APCGK-${tripNumberBase + index * 2}`
    return `  ('${esc(id)}', '${esc(stationId)}', '${esc(tripNumber)}', '${time}', '${time}',`
      + ` '${esc(boundFor)}', '${esc(line)}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)`
  })

  /*
   * The delete makes re-applying a file safe on an already-loaded station.
   * Scoped by id pattern (station + line + direction) so the opposite
   * direction's rows at the same station survive.
   */
  const clearStatement = `DELETE FROM schedules WHERE id LIKE '${esc(stationId)}-${esc(line)}-%-${esc(dest)}';\n`
  const insertStatement = 'INSERT INTO schedules (id, stationId, tripNumber, estimatedDeparture, estimatedArrival, boundFor, lineCode, createdAt, updatedAt) VALUES\n'
  const switchTimetableSynced = `UPDATE stations SET timetableSynced = 1 WHERE id = '${esc(stationId)}';\n`

  const header = `-- ${stationId} -> ${boundFor} (${times.length} departures)\n`
    + '-- GENERATED by generateTimetableSQL.ts from timetables/*.csv — do not edit by hand.\n'

  return header + clearStatement + insertStatement + rows.join(',\n') + ';\n\n' + switchTimetableSynced
}

function main(): void {
  if (!fs.existsSync(INPUT_DIR)) {
    console.error(`Input directory not found: ${INPUT_DIR}`)
    process.exit(1)
  }

  const csvFiles = fs.readdirSync(INPUT_DIR).filter(file => file.endsWith('.csv'))
  if (csvFiles.length === 0) {
    console.error(`No CSV files in ${INPUT_DIR}. Expected <STATION>_<LINE>_<DEST>.csv, e.g. T1_KLB_T3.csv.`)
    process.exit(1)
  }

  const errors: string[] = []
  const written: string[] = []
  const parsedFiles: { key: TimetableFileKey, times: string[] }[] = []

  for (const file of csvFiles.sort()) {
    const key = parseTimetableFilename(file)
    if ('error' in key) {
      errors.push(key.error)
      continue
    }

    const lines = fs.readFileSync(path.join(INPUT_DIR, file), 'utf8').split(/\r?\n/)
    const times: string[] = []
    let fileHasErrors = false
    for (const [index, line] of lines.entries()) {
      if (!line.trim()) continue
      const time = normalizeTime(line)
      if (!time) {
        errors.push(`${file}:${index + 1} invalid time "${line.trim()}" (expected H:MM or HH:MM)`)
        fileHasErrors = true
        continue
      }
      if (times.length > 0 && time <= times[times.length - 1]!) {
        errors.push(`${file}:${index + 1} time ${time} is not after the previous departure`)
        fileHasErrors = true
        continue
      }
      times.push(time)
    }

    if (fileHasErrors) continue
    if (times.length === 0) {
      errors.push(`${file} contains no departures`)
      continue
    }

    parsedFiles.push({ key, times })
  }

  /*
   * Trip numbers are assigned by CSV line index, which identifies the same
   * vehicle across stations only if every trip serves every station. The
   * Kalayang runs a single 13-minute cadence end to end, so that holds — but
   * assert it rather than assume: a count mismatch within a direction means a
   * short working or a transcription slip, and misaligned numbers would claim
   * two different trains are the same one.
   */
  const countsByDirection = new Map<string, Set<number>>()
  for (const { key, times } of parsedFiles) {
    const direction = `${key.line}_${key.dest}`
    const counts = countsByDirection.get(direction) ?? new Set<number>()
    counts.add(times.length)
    countsByDirection.set(direction, counts)
  }
  for (const [direction, counts] of countsByDirection) {
    if (counts.size > 1) {
      errors.push(`${direction} CSVs disagree on departure count (${[...counts].sort((a, b) => a - b).join(' vs ')}) — trip numbers cannot align by index`)
    }
  }

  if (!errors.some(error => error.includes('cannot align'))) {
    for (const { key, times } of parsedFiles) {
      const outputPath = path.join(OUTPUT_DIR, `apcgk_${key.station}_${key.line}_${key.dest}_timetable.sql`)
      fs.writeFileSync(outputPath, buildTimetableSQL(key.station, key.line, key.dest, times))
      written.push(`${outputPath} (${times.length})`)
    }
  }

  for (const line of written) console.log(`Wrote ${line}`)

  if (errors.length > 0) {
    console.error(`\n${errors.length} error(s):`)
    for (const error of errors) console.error(`  ${error}`)
    process.exit(1)
  }
}

if (require.main === module) {
  main()
}
