import { resolve } from 'node:path'
import tailwindcss from '@tailwindcss/vite'
import { defineConfig } from 'vite'

export default defineConfig({
  plugins: [tailwindcss()],
  build: {
    outDir: 'dist',
    rollupOptions: {
      input: {
        // docs.html is generated by scripts/build-docs.ts before the build —
        // see the `build` script. It is an input here so Tailwind and the
        // bundler process it like any other page.
        //
        // Both entries import src/wordmark.ts (the homepage via
        // scene/network-scene.ts, the reference via docs-field.ts), so Rollup
        // splits it into a shared chunk. That is left alone deliberately: it is
        // modulepreloaded rather than serially fetched, and merging it back is
        // not something manualChunks or experimentalMinChunkSize will do for a
        // module both entries genuinely share.
        main: resolve(import.meta.dirname, 'index.html'),
        docs: resolve(import.meta.dirname, 'docs.html')
      }
    }
  }
})
