import { resolve } from 'node:path'
import tailwindcss from '@tailwindcss/vite'
import { defineConfig } from 'vite'

export default defineConfig({
  plugins: [tailwindcss()],
  build: {
    outDir: 'dist',
    rollupOptions: {
      input: {
        // docs.html is generated by scripts/build-docs.ts before the build —
        // see the `build` script. It is an input here so Tailwind and the
        // bundler process it like any other page.
        main: resolve(import.meta.dirname, 'index.html'),
        docs: resolve(import.meta.dirname, 'docs.html')
      }
    }
  }
})
