import * as fs from 'node:fs'
import * as path from 'node:path'
import { HOLIDAYS } from '@commute/constants'

/*
 * Writes the constants the Android app needs as Kotlin, so they reach it from
 * @commute/constants rather than being copied by hand and left to drift.
 *
 * Checked in, like the OpenAPI snapshot, so an Android build needs neither this
 * workspace nor a network. Rerun after editing any constant exported here; the
 * yearly HOLIDAYS update is the one that is easy to forget.
 */
const TARGET = path.resolve(
  __dirname,
  '../../../android/core/common/src/main/java/id/shiorilabs/commute/core/constants/Holidays.kt'
)

const holidays = [...HOLIDAYS].sort()

const source = `package id.shiorilabs.commute.core.constants

// GENERATED by \`pnpm --filter @commute/api android:constants\` from HOLIDAYS in
// apps/constants/src/index.ts. Edit it there and rerun; changes here are overwritten.

/**
 * Indonesian national holidays, as local \`YYYY-MM-DD\`. Holidays run a Sunday-shaped service, so
 * the service day of a date in here is SUN.
 */
val HOLIDAYS: Set<String> = setOf(
${holidays.map(date => `    "${date}",`).join('\n')}
)
`

fs.mkdirSync(path.dirname(TARGET), { recursive: true })
fs.writeFileSync(TARGET, source)
console.log(`Wrote ${holidays.length} holidays to ${path.relative(process.cwd(), TARGET)}`)
