import * as fs from 'node:fs'
import * as path from 'node:path'
import { AMENITY_TYPES, HOLIDAYS, OPERATORS } from '@commute/constants'

/*
 * Writes the constants the Android app needs as Kotlin, so they reach it from
 * @commute/constants rather than being copied by hand and left to drift.
 *
 * Checked in, like the OpenAPI snapshot, so an Android build needs neither this
 * workspace nor a network. Rerun after editing any constant exported here; the
 * yearly HOLIDAYS update is the one that is easy to forget.
 */
const CONSTANTS_DIR = path.resolve(
  __dirname,
  '../../../android/core/common/src/main/java/id/shiorilabs/commute/core/constants'
)

function write(file: string, source: string, summary: string) {
  const target = path.join(CONSTANTS_DIR, file)
  fs.mkdirSync(path.dirname(target), { recursive: true })
  fs.writeFileSync(target, source)
  console.log(`Wrote ${summary} to ${path.relative(process.cwd(), target)}`)
}

const holidays = [...HOLIDAYS].sort()

const holidaysSource = `package id.shiorilabs.commute.core.constants

// GENERATED by \`pnpm --filter @commute/api android:constants\` from HOLIDAYS in
// apps/constants/src/index.ts. Edit it there and rerun; changes here are overwritten.

/**
 * Indonesian national holidays, as local \`YYYY-MM-DD\`. Holidays run a Sunday-shaped service, so
 * the service day of a date in here is SUN.
 */
val HOLIDAYS: Set<String> = setOf(
${holidays.map(date => `    "${date}",`).join('\n')}
)
`

write('Holidays.kt', holidaysSource, `${holidays.length} holidays`)

const amenities = Object.entries(AMENITY_TYPES)

const amenitiesSource = `package id.shiorilabs.commute.core.constants

// GENERATED by \`pnpm --filter @commute/api android:constants\` from AMENITY_TYPES in
// apps/constants/src/index.ts. Edit it there and rerun; changes here are overwritten.

/**
 * A station facility's label by its API type (\`TOILET\` → "Toilet"). The API adds types without
 * notice, so a lookup can miss: fall back to the type itself.
 */
val AMENITY_LABELS: Map<String, String> = mapOf(
${amenities.map(([type, label]) => `    "${type}" to ${JSON.stringify(label)},`).join('\n')}
)
`

write('Amenities.kt', amenitiesSource, `${amenities.length} amenity labels`)

// NUL is an internal placeholder the API never sends.
const operators = Object.values(OPERATORS).filter(operator => operator.code !== 'NUL')

const operatorsSource = `package id.shiorilabs.commute.core.constants

// GENERATED by \`pnpm --filter @commute/api android:constants\` from OPERATORS in
// apps/constants/src/index.ts. Edit it there and rerun; changes here are overwritten.

/**
 * An operator's name by its API code (\`KCI\` → "Commuter Line"). The API adds operators without
 * notice, so a lookup can miss: fall back to the code itself.
 */
val OPERATOR_NAMES: Map<String, String> = mapOf(
${operators.map(operator => `    "${operator.code}" to ${JSON.stringify(operator.name)},`).join('\n')}
)
`

write('Operators.kt', operatorsSource, `${operators.length} operator names`)
